Update 0-custom_http_response_header

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -3,28 +3,25 @@
 
 echo -e "Updating and doing some minor checks...\n"
 
-function install() {
-    command -v "$1" &> /dev/null
-
-    #shellcheck disable=SC2181
-    if [ $? -ne 0 ]; then
+# Check and install nginx if not installed
+check_and_install() {
+    if ! command -v "$1" &> /dev/null; then
         echo -e "    Installing: $1\n"
-        sudo apt-get update -y -qq && \
-            sudo apt-get install -y "$1" -qq
+        sudo apt-get update -y -qq && sudo apt-get install -y "$1" -qq
         echo -e "\n"
     else
         echo -e "    $1 is already installed.\n"
     fi
 }
 
-install nginx
+check_and_install nginx
 
 echo -e "\nSetting up some minor stuff.\n"
 
-# allowing nginx on firewall
+# Allow Nginx HTTP traffic on the firewall
 sudo ufw allow 'Nginx HTTP'
 
-# Give the user ownership to website files for easy editing
+# Ensure the user has ownership and permissions for the website files
 if [ -d "/var/www" ]; then
     sudo chown -R "$USER":"$USER" /var/www
     sudo chmod -R 755 /var/www
@@ -34,23 +31,22 @@ else
     sudo chmod -R 755 /var/www
 fi
 
-# create directories if not present
+# Create necessary directories if they don't exist
 for dir in /var/www/{html,error}; do
     if ! [ -d "$dir" ]; then
-        mkdir -p "$dir"
+        sudo mkdir -p "$dir"
     fi
 done
 
-# creating new index
-echo "Hello World!" > /var/www/html/index.html
+# Create the index and error pages
+echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null
+echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html >/dev/null
 
-# create new error page
-echo "Ceci n'est pas une page" > /var/www/html/error_404.html
-
-# backup default server config file
+# Backup the default Nginx server configuration
 sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
 
-server_config="
+# Generate the new server configuration
+server_config=$(cat <<EOF
 server {
     listen 80 default_server;
     listen [::]:80 default_server;
@@ -68,12 +64,15 @@ server {
     location = /error_404.html {
         internal;
     }
-}"
+}
+EOF
+)
 
-#shellcheck disable=SC2154
+# Apply the new server configuration
 echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
 
-if [ "$(pgrep -c nginx)" -le 0 ]; then
+# Restart Nginx if it's running, or start it if it's not
+if ! pgrep -c nginx &> /dev/null; then
     sudo service nginx start
 else
     sudo service nginx restart
