Update 101-manage_my_process

diff --git a/0x05-processes_and_signals/101-manage_my_process b/0x05-processes_and_signals/101-manage_my_process
--- a/0x05-processes_and_signals/101-manage_my_process
+++ b/0x05-processes_and_signals/101-manage_my_process
@@ -1,33 +1,71 @@
 #!/usr/bin/env bash
-# This script manages manage_my_process
+# This script will manages manage_my_process
 
-PIDFILE=/var/run/my_process.pid
+is_process_running() {
+    pgrep -f ./manage_my_process > /dev/null
+    return $?
+}
 
-start() {
+start_process() {
     ./manage_my_process &
-    echo "$!" > "$PIDFILE"
+    sleep 1
+    is_process_running
+    if [ $? -eq 0 ]; then
+        sudo tee /var/run/my_process.pid <<< "$!"
+        return 0
+    else
+        return 1
+    fi
 }
 
-stop() {
-    sudo kill -15 "$(cat "$PIDFILE")" && rm -f "$PIDFILE"
+stop_process() {
+    pkill -f ./manage_my_process
+    sleep 1
+    is_process_running
+    if [ $? -ne 0 ]; then
+        sudo rm -f /var/run/my_process.pid
+    fi
 }
 
-case "$1" in 
+case "$1" in
     start)
-       start
-       echo "manage_my_process started"
-       ;;
+        is_process_running
+        if [ $? -eq 0 ]; then
+            echo 'manage_my_process is already running'
+        else
+            start_process
+            if [ $? -eq 0 ]; then
+                echo 'manage_my_process started'
+            else
+                echo 'Failed to start manage_my_process'
+            fi
+        fi
+        ;;
     stop)
-       stop
-       echo "manage_my_process stopped"
-       ;;
+        is_process_running
+        if [ $? -eq 0 ]; then
+            stop_process
+            echo 'manage_my_process stopped'
+        else
+            echo 'manage_my_process is not running'
+        fi
+        ;;
     restart)
-       stop
-       start
-       echo "manage_my_process restarted"
-       ;;
+        is_process_running
+        if [ $? -eq 0 ]; then
+            stop_process
+        fi
+        start_process
+        if [ $? -eq 0 ]; then
+            echo 'manage_my_process restarted'
+        else
+            echo 'Failed to restart manage_my_process'
+        fi
+        ;;
     *)
-       echo "Usage: manage_my_process {start|stop|restart}"
+        echo 'Usage: manage_my_process {start|stop|restart}'
+        exit 1
+        ;;
 esac
 
-exit 0
+exit $?
